# -*- coding: utf-8 -*-
"""numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdKe3MxFageOJpi0d182T8QAjcpB6hW1
"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

import numpy as np

arr = np.array(42)

print(arr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)